### ISSUE TITLE
Trailing comma before a new line can't be fixed

### ISSUE THREAD

**Issue by SvetozarMateev** [Berkmann18/json-fixer#18]
## Expected behaviour
The json should be fixed
## Actual behaviour
The following error is thrown:

There's still an error!
...\node_modules\json-fixer\index.js:28
    throw new Error(err.message)
    ^

Error: Expected string but "}" found.

## How to reproduce
This json fails always.
```js
[
    {
        "test1": "1",
        "test2": {
            "a": "b",
            "c": {

            },

        }
    }
]
```

## Possible solution(s)
I've debugged the code a bit and found out that the target line in the  **fixJson** method in index.js
isn't always ```start.line-2``` in this case it should be **-3** so I assume that there is a problem with the code that generates the error - **json.pjs**

## Environment

- Version: 1.3.2
- OS(s): Windows 10
- Node version: 10.16.0
- NPM version: 6.9.0

**Comment by Berkmann18** [comment]
Thank you for reporting that error, I've tweaked the code and will add your example to the tests and push it as soon as it passes and then I'll try to get it to `master` asap.

**Comment by Berkmann18** [comment]
@all-contributors Please add @SvetozarMateev for bugs.
