### ISSUE TITLE
doesn't work 

### ISSUE THREAD

**Issue by jpike88** [Berkmann18/json-fixer#25]
UnhandledPromiseRejectionWarning: Error: Unsupported issue: Expected "[", "false", "null", "true", "{", number, or string but "\"" found. (please open an issue at the repo)

**Comment by Berkmann18** [comment]
Hi @jpike88, thanks for opening an issue.
Would it be possible for you to provide the information asked in the [issue template](https://github.com/Berkmann18/json-fixer/issues/new?labels=Type%3A+Bug+%3Abug%3A%2C+Priority%3A+Medium&template=BUG.md) so I can properly help you?

**Comment by Berkmann18** [comment]
Friendly ping @jpike88.

**Comment by jpike88** [comment]
Sorry mate I have zero time to scratch my butt! Don't worry it was some weird edge case I already forgot how/why

**Comment by Berkmann18** [comment]
@jpike88 Hmm, okay! If you remember or come across that edge case, please open an issue with the all details needed (and feel free to submit a PR if you want) :grinning:.
