### ISSUE TITLE
Not able to fix this JSON

### ISSUE THREAD

**Issue by andre-paulo98** [Berkmann18/json-fixer#31]
With this JSON as input: `{something:"string:string"}` it fails with this error: (enabled verbose) https://gist.github.com/andre-paulo98/746f77c4306f180b02f70c00ff474455

The website https://jsonformatter.curiousconcept.com/ is able to fix this JSON:
![image](https://user-images.githubusercontent.com/19685105/83978107-0c03f680-a8fd-11ea-83d0-33ca300c8ca5.png)

## Environment

- Version: 1.4.1
- OS(s): Windows 10
- Node version: 12.16.2
- NPM version: 4.14.4

**Comment by Berkmann18** [comment]
Thanks for opening the issue, and indeed the fixer wasn't able to fix such issues compared to other _kinds_ of left-hand-side missing quotes issues.
I've added your example as a sample (which is used in the test suite) and so far it has been able to fix that issue while still being able to fix the others.

**Comment by Berkmann18** [comment]
@all-contributors Please add @andre-paulo98 for bug.
