### ISSUE TITLE
Can't parse missing quotes

### ISSUE THREAD

**Issue by Erkin97** [Berkmann18/json-fixer#35]
```
Error: Unsupported issue: Expected end of input but "s" found. (please open an issue at the repo)
```

Can't parse missing quotes. Any example won't work

**Comment by Berkmann18** [comment]
@Erkin97 Which examples? The ones used in the test suite which can be found in [samples](https://github.com/Berkmann18/json-fixer/tree/master/test/samples)?

**Comment by Erkin97** [comment]
I tried to run it as follow:

```javascript
const jsonFix = require('json-fixer');

jsonFix('{field: value}');
```

thanks!

**Comment by Berkmann18** [comment]
@Erkin97 Okay, thank you! I believe I spotted the error, and I have a solution in mind which may not be published until later today.

@all-contributors Please add @Erkin97 for bug
