### ISSUE TITLE
Unsupported issue: Expected end of input but "}" found.

### ISSUE THREAD

**Issue by GiraffeKey** [Berkmann18/json-fixer#47]
## Proposal
If there are too many closing brackets, remove as many as needed.

**Comment by GiraffeKey** [comment]
This is an implementation I wrote in Lodash, shouldn't be hard to translate to normal JS.
```js
const bracketDiff = (_.countBy(string)['}'] || 0) - (_.countBy(string)['{'] || 0);

_.each(_.range(bracketDiff), () =>
	string.slice(_.lastIndexOf(string, '}'), 1))
```

**Comment by Berkmann18** [comment]
@GiraffeKey That's a great idea, feel free to submit a PR for this 😄.

**Comment by GiraffeKey** [comment]
That code was actually broken because I was getting `slice` and `splice` mixed up.
```js
const bracketDiff = (_.countBy(string)["}"] || 0) - (_.countBy(string)["{"] || 0);
					
.each(_.range(bracketDiff), () => {
	const index = _.lastIndexOf(string, "}");
	string = string.slice(0, index) + string.slice(index + 1);
});
```
This is working for me. I'll look into getting a PR submitted.
